# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2824c701ae11f980980ba5c9901e9f5b3db593c525382612c578515abbc44451a92f7e718c7846c4f9c861a4743a354433c48d20fe5aa31cc19862f74bea124d

test:
  secret_key_base: 8b305494d1053fba8762fe8e8a738deda87ad6af2cdb492f0877af2ddb491be4309aca8bc45f89bbd1cea87115bec6cca3544f8edaaeaa020d716e9282e3eec9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
